### ISSUE TITLE
Parameterized SQL queries with IN keyword

### ISSUE THREAD

**Issue by yvele** [Azure/azure-documentdb-node#156] opened 2016-12-15 16:01 UTC
Are [parameterized SQL](https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sql-query#parameterized-sql-queries) with [IN keyword](https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sql-query#in-keyword) supposed to be working?

Neither this

```js
{      
    query: "SELECT * FROM root r WHERE r.foo IN (@bar)",     
    parameters: [          
        { name: "@bar", value: ["a", "b", "c"] }       
    ] 
}
```

or this

```js
{      
    query: "SELECT * FROM root r WHERE r.foo IN @bar",     
    parameters: [          
        { name: "@bar", value: ["a", "b", "c"] }       
    ] 
}
```

are working.. They gives a syntax error.

PS: [Parameterized SQL query documentation](https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sql-query#parameterized-sql-queries) states that:

> Parameter values can be any valid JSON (strings, numbers, Booleans, null, **even arrays** or nested JSON). Also since DocumentDB is schema-less, parameters are not validated against any type.

Any workaround other than the [usual SQL server hack](http://stackoverflow.com/a/337792/1480391)?

**Comment by moderakh** [comment] 2017-02-10 00:15
@yvele a workaround to this is to rewrite the query as:

```
{      
    query: "SELECT * FROM root r WHERE ARRAY_CONTAINS(@bar, r.foo)",     
    parameters: [          
        { name: "@bar", value: ["a", "b", "c"] }       
    ] 
}
```

**Comment by moderakh** [comment] 2017-02-10 00:17
I am closing this as it is not an issue, if still it doesn't work for you please reopen/comment.

**Closed by moderakh** 2017-02-10 00:17 UTC
Labels: question

**Comment by JannesV** [comment] 2019-04-03 14:24
I can confirm this is still an issue, the workaround works but it's not very clear. Seeing there is no documentation surrounding this whatsoever.

**Comment by pebo** [comment] 2019-04-15 10:18
Any plans for adding parameter support for IN queries or documenting the known limitations and workarounds?

**Comment by bingbing8** [comment] 2019-08-01 19:32
ARRAY_CONTAINS does not work for me either

**Comment by vathakur** [comment] 2019-08-08 01:08
@bingbing8 ARRAY_CONTAINS works for me. Mistake that I was doing before was to enclose the array in double quotes and values in single quotes like `"['aa448e10-88a7-448a-b385-124d02624ffe', '1fccbe54-6ed0-4c88-87ad-2b10d86d8990', `'6082b3bf-c472-4a30-a387-24c18495e6ba']"
However, it works like below
`["aa448e10-88a7-448a-b385-124d02624ffe", "1fccbe54-6ed0-4c88-87ad-2b10d86d8990", "6082b3bf-c472-4a30-a387-24c18495e6ba"]`.
Don't enclose the complete array in qoutes and use double quotes for values.

**Comment by VladislavDubrovenski** [comment] 2024-08-21 18:54
For those who got here looking for C# solution, just pass the list of strings, don't convert to string, it works with just a list
