### ISSUE TITLE
sproc, trigger and udf property definitions mismatch online docs

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-documentdb-node#162] opened 2016-12-23 01:11 UTC
https://docs.microsoft.com/en-us/azure/documentdb/documentdb-programming

`name` (docs) --> `id` (SDK)
`body` (docs) --> `serverScript` (SDK)

**Comment by moderakh** [comment] 2017-02-10 00:30
@1N50MN14 could you please elaborate more what the issue is here? 
@mimig1 @emilylawton could you please take a look.

**Comment by 1N50MN14** [comment] 2017-02-10 00:35
@moderakh It's just a small mismatch between the online documentation and actual SDK API for sprocs and triggers

**Comment by mimig1** [comment] 2017-02-10 03:18
@1N50MN14 - It looks like you know how to use git - are you interested in submitting a pull request to the doc page to make the fix? Just go to the article page, click the Edit button in the upper right corner, click the Pencil button in the upper right, make your change and click Create Pull Request a few times. We'll get the PR, review it and accept it if it all looks good.

**Comment by 1N50MN14** [comment] 2017-02-10 05:23
@mimig1 Sure thing, https://github.com/Microsoft/azure-docs/pull/697

**Comment by moderakh** [comment] 2017-02-10 18:49
Thank you @1N50MN14 for reporting this and your patch for fixing the documentation. As this is an issue in the documentation, I am closing it here, let's track this in the azure docs repo.

**Closed by moderakh** 2017-02-10 18:49 UTC
