### ISSUE TITLE
Can not connect to documentdb

### ISSUE THREAD

**Issue by ravievontech** [Azure/azure-documentdb-node#245] opened 2018-07-06 10:06 UTC
I am not able to connect to azure documentdb. Its throwing error:

{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1092:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: null,
  host: 'orion-cosmos.documents.azure.com',
  port: '10255',
  localAddress: undefined }

**Comment by srinathnarayanan** [comment] 2018-07-09 19:14
Hi @ravievontech how often are you seeing this issue? Can you connect to the service now?

**Comment by so-ravindra** [comment] 2018-07-10 06:33
@srinathnarayanan the issue is resolved. The problem was the port i was using.

**Comment by ravievontech** [comment] 2018-07-10 06:35
@srinathnarayanan Hi, the problem is resolved. The problem was the port i was using. Thanks

**Comment by srinathnarayanan** [comment] 2018-07-10 18:11
Will close this issue. Thanks.

**Closed by srinathnarayanan** 2018-07-10 18:11 UTC
