### ISSUE TITLE
Socket keep-alive and server reset

### ISSUE THREAD

**Issue by pierre-elie** [Azure/azure-documentdb-node#102] opened 2016-02-01 18:03 UTC
The HTTPS agent used to request DocumentDB [is using Keep-Alive](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/request.js#L37) for its pool of sockets.

- issue 1: after ~2 minutes of inactivity, the remote DocumentDB server closes the connection (although the socket is _kept-alive_), resulting in the socket throwing an `ECONNRESET` error
- issue 2: no listener is set for socket’s `error` event, therefore the error is thrown

Result: after ~2 minutes of inactivity, the sdk throws an `ECONNRESET` error, although from an sdk client point-of-view it’s being used in normal conditions.

I would suggest handling socket errors at the sdk level, specially since it’s the sdk stand to keep sockets alive, resulting in this 2 minutes "time-out".
(I’m referencing [this part](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/request.js#L92-L104) of the request code)

A quick and dirty fix for this 2 minutes issue could be to "mute" `ECONNRESET` errors:
```js
socket.on('error', function(err) {
  if (err.code !== 'ECONNRESET') throw err;
});
```
But again, it would mean all other socket errors would still be thrown, which might not be great.

**Comment by ryancrawcour** [comment] 2016-02-02 21:56
What version of Node.js are you using? 
Do you have a repro for this issue?

**Comment by JanneSalo** [comment] 2016-02-03 07:40
For me it occurs at least with node v4.2.3. In my use case, my app queries for a stored procedure object on startup and caches it. The app may idle for quite some time before it needs anything from DocumentDB. Pretty much exactly after two minutes after startup, the app crashes due to an unhandled `ECONNRESET` error.

**Comment by JanneSalo** [comment] 2016-02-03 13:10
Here's a simple way to reproduce the issue:

```javascript
var DocumentClient = require('documentdb').DocumentClient;

var host = ""; // Add your endpoint
var masterKey = "";  // Add the massterkey of the endpoint
var client = new DocumentClient(host, {masterKey: masterKey});

//Query something to open the connection
client.queryDatabases("SELECT * FROM root r WHERE r.id = 'mydb'").toArray(function(err, result) {
	console.log(err, result);
});

//Do something every 30 secs, just to keep the node process running
setInterval(function() {
	console.log('still alive!');
}, 30000);
```
After two minutes, this will throw an unhandled `ECONNRESET` error and crash when using `documentdb` v1.5.5

**Comment by ryancrawcour** [comment] 2016-02-03 19:34
@JanneSalo unfortunately the code provided does not repro the problem on my end. 

![capture](https://cloud.githubusercontent.com/assets/1082796/12794454/01e8f072-ca6a-11e5-9e98-1ce693cd554b.PNG)

did i misunderstand?

**Comment by JanneSalo** [comment] 2016-02-04 06:22
I'd imagine the underlying OS matters. I guess sockets are handled differently on OS level in Windows than they are in *NIX systems. On OS X and Linux, the problem is easily reproduced by the code.

**Comment by ryancrawcour** [comment] 2016-02-04 06:26
Will try repro on Linux and OSX

**Comment by pierre-elie** [comment] 2016-02-04 15:58
After reproducing @JanneSalo’s example on 4.2.6 but not 5.5.0, I went testing other versions.
**It seems the issue has been solved in node 5.4.0 by https://github.com/nodejs/node/pull/4482.**

To be exact, the fix avoids throwing the error happening on the idle socket, it does not address why an error is happening in the first place. I’m ok to close though.

**Comment by ryancrawcour** [comment] 2016-02-04 16:13
That would explain why I cannot reproduce.

**Comment by ryancrawcour** [comment] 2016-02-26 22:46
@JanneSalo can you please confirm that using a newer version of node would help address this for you

**Comment by JanneSalo** [comment] 2016-02-29 06:19
Yes, using node v5.5.0 does indeed help.

**Comment by ryancrawcour** [comment] 2016-02-29 17:48
Closing this issue as this was fixed in Node v5

**Closed by ryancrawcour** 2016-02-29 17:48 UTC
Labels: investigating

**Comment by kenstone** [comment] 2016-03-21 02:20
@ryancrawcour While upgrading to node 5 works, if running the app in AWS Elastic Beanstalk, which currently only supports up to node 4.3.0, the problem is unavoidable. Right now I'm hoping for them to upgrade to node 4.4.0 (which now also has the fix).

**Comment by ryancrawcour** [comment] 2016-03-21 03:12
How are you running DocumentDB in AWS? I can't imagine cross region / data center provides very good performance. 

PS. Azure mobile apps supports Node.js 5 :)

**Comment by mwawrusch** [comment] 2016-08-23 23:19
Can you please reopen this issue - some people are forced to run this on 4.3.2 on AWS Lambda.

**Comment by mwawrusch** [comment] 2016-08-24 14:02
@dmoreno That doesn't help - talking about AWS Lambda, not Azure Web Roles..

**Comment by dmoreno** [comment] 2016-08-25 06:15
@mwawrusch #137 and #102 issues are simply related (same error, different environment) not duplicated issues.

**Comment by mwawrusch** [comment] 2016-08-25 19:05
@dmoreno got it. Unfortunately that makes it impossible for us to use documentdb - it's a shame as Microsoft was always super strong with databases.

**Comment by lilyS123** [comment] 2017-09-27 21:16
I have ECONNRESET errors thrown by document db client running node version 6.11.2 on VirtualBox with Windows10 installed.

**Comment by alohaninja** [comment] 2017-12-29 21:43
I'm getting frequent ECONNRESET errors with node v8.2.1 on Win 10 using documentdb 1.12.2 package.  `documentClient.upsertDocument` results in the error below: 

``` 
{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
```

**Comment by vikashkumarjangid** [comment] 2020-07-20 17:32
Hi Getting the same error in Azure function app. 

After the 2 minutes to function completion, I got the same error. I am using MongoDb .
